server:
  port: 8080

spring:
  datasource:
    # 当前激活的数据源
    active: mysql

dbconfig:
  datasources:
    mysql:
      name: MySQL数据库
      url: jdbc:mysql://10.203.88.206:3306/fs_cia?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: kcia
      password: kcia
    sqlserver:
      name: SQLServer数据库
      url: jdbc:sqlserver://10.203.88.206:1433;DatabaseName=fs_cia
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      username: sa
      password: 1qaz@WSX
    postgresql:
      name: PostgreSQL数据库
      url: jdbc:postgresql://localhost:5432/test
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: postgres
    oracle:
      name: Oracle数据库
      url: jdbc:oracle:thin:@localhost:1521:XE
      driver-class-name: oracle.jdbc.OracleDriver
      username: system
      password: oracle
    sqlite:
      name: SQLite数据库
      url: jdbc:sqlite:test.db?cache_size=5000000&journal_mode=WAL
      driver-class-name: org.sqlite.JDBC
      username: root
      password: root
    duckdb:
      name: DuckDB数据库
      url: jdbc:duckdb:test.duckdb
      driver-class-name: org.duckdb.DuckDBDriver
      username: root
      password: root
    sqliteInMemory:
      name: SQLite内存数据库
      url: "jdbc:sqlite::memory:"
      driver-class-name: org.sqlite.JDBC
      username: root
      password: root
    duckdbInMemory:
      name: DuckDB内存数据库
      url: "jdbc:duckdb::memory:"
      driver-class-name: org.duckdb.DuckDBDriver
      username: root
      password: root
    gaussdb:
      name: GaussDB数据库
      url: jdbc:postgresql://10.203.88.206:5432/fs_cia?currentSchema="fs_das"&targetServerType=master&connectTimeout=2&loginTimeout=6
      driver-class-name: com.huawei.gauss.jdbc.Driver
      username: kcia
      password: kcia

# Druid连接池配置
druid:
  initial-size: 10
  min-idle: 5
  max-active: 20
  max-wait: 60000

# 压测配置
stress:
  thread-pool:
    core-size: 10
    max-size: 20
    queue-capacity: 100
  duration: 300
  sample-rate: 3
  sql:
    file-path: classpath:sql/test.sql
    params-path: classpath:sql/params.csv
  report: log   # 可选值：log, console


jdbc:
  driver:
    path: classpath*:jdbc/*.jar  # JDBC驱动目录路径，默认为应用根目录下的jdbc文件夹

logging:
  file:
    name: logs/spring-boot.log  # 指定日志文件的名称和路径
  level:
    root: INFO  # 设置全局日志级别